FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY favicons/ /usr/share/nginx/html/favicons/
COPY v1/index.html /usr/share/nginx/html/v1/index.html
COPY v2/index.html /usr/share/nginx/html/v2/index.html
COPY favicons/ /usr/share/nginx/html/v1/favicons/
COPY favicons/ /usr/share/nginx/html/v2/favicons/
EXPOSE 80
COPY v3/index.html /usr/share/nginx/html/v3/index.html
COPY v4/index.html /usr/share/nginx/html/v4/index.html
COPY v5/index.html /usr/share/nginx/html/v5/index.html
COPY v6/index.html /usr/share/nginx/html/v6/index.html
COPY favicons/ /usr/share/nginx/html/v3/favicons/
COPY favicons/ /usr/share/nginx/html/v4/favicons/
COPY favicons/ /usr/share/nginx/html/v5/favicons/
COPY favicons/ /usr/share/nginx/html/v6/favicons/
COPY v7/index.html /usr/share/nginx/html/v7/index.html
